{% set name = "onnx-caffe2" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef4ba9a71798b7a5dd0a1897fb33eddd7bba148236a01abf0a0dc160e98bf020

build:
  number: 1004
  noarch: python
  script:
    - pip install -e . -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - onnx
    - click
    # NB: caffe2 is not conda managed, so don't put it as a "dep"

test:
  # It would be nice to do this, but a user has to have independently
  # installed caffe2 for this to work.
  # imports:
  #  - onnx_caffe2

  # This appeases the linter (which requires a test), and eventually
  # we're going to build some C++ in this package, which will be helpful
  commands:

about:
  home: https://github.com/onnx/onnx-caffe2/
  license: MIT
  license_family: MIT
  license_file: LICENSE  # https://github.com/onnx/onnx-caffe2/pull/81
  summary: Caffe2 implementation of Open Neural Network Exchange (ONNX)
  description: |
    This library provides Caffe2 importer and exporter for the ONNX format.

extra:
  recipe-maintainers:
    - ezyang
    - xhochy
