appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NYiUPtsdAt8UMBYGXI8c1o51v0HVCNbS8GxEuWMmC4s2ms817qwOCkKLlWOA5ZK2IxLFOe0WuBb4vTWgCRck1WlWPNcnQBH5xRP3+0BAOJnHp17b7SQWOixK22RPpmJtwEKXk2IkP3FGGxMjbSSc3ivwMFP/+kijKP62JapOKvr2SV6ENjobA/b1XK/2mK0NHbyMEOGMoheqOWgLo6QSY2CX1FnHTOgsE5PfHewokgDRtf6ZTqvBTr/4G5BkgpBiNY1fZjhb1sk2EXAAvI87jALi0E0r55G0WmI2LRka+y5SNxHfmF/86puHiZR58Sm2q78aR11GRKyNuqJ5eq67E2g6YGYlxdQ1sUuXllszTGEnBw52lU0s/Kxy+gX8ItuWoClhnL0aHaULSZ+B+cb5nWLTDpV1c9X5Lfxuo6vsyGTgAfJxNUEbzWt9Gt3DdvD2MKiLFeycd9W6H+6kuwk0hyiZ05N1Y9KOqOA0A1HXOzgDy6SLg58Rji1RDcHg5lBmLwxWoO9qZFSmAsECorB4E7CrMw3ItwVkh89Wwkv3RSHees30Q9e9zXmbWCsHa7hyvTwHOZ/5ckzy3LGtNh5N6bCIP2pTmTxh8N3+ZNEPzcvQ/ElPXlC6Y75vtlOVQPlaKQNmetzAg0fyysEeri6Q/OMvMb0Xr9z5mVz0yZZkMNQ=}
provider:
  win: azure
conda_forge_output_validation: true
